import { NgModule } from '@angular/core';
import { 
    MatButtonModule, 
    MatIconModule, 
    MatFormFieldModule, 
    MatInputModule, 
    MatDatepickerModule, 
    MatNativeDateModule, 
    MatCheckboxModule, 
    MatSidenavModule, 
    MatToolbarModule, 
    MatListModule, 
    MatTabsModule, 
    MatCardModule, 
    MatSelectModule, 
    MatTableModule, 
    MatSortModule, 
    MatRadioModule, 
    MatDialogModule, 
    MatBadgeModule } from '@angular/material';

@NgModule ({
    imports: [
        MatButtonModule, 
        MatIconModule, 
        MatFormFieldModule, 
        MatInputModule, 
        MatDatepickerModule, 
        MatNativeDateModule, 
        MatCheckboxModule, 
        MatSidenavModule, 
        MatToolbarModule, 
        MatListModule, 
        MatTabsModule, 
        MatCardModule, 
        MatSelectModule, 
        MatTableModule, 
        MatSortModule, 
        MatRadioModule, 
        MatDialogModule, 
        MatBadgeModule],
    exports: [
        MatButtonModule, 
        MatIconModule, 
        MatFormFieldModule, 
        MatInputModule, 
        MatDatepickerModule, 
        MatNativeDateModule, 
        MatCheckboxModule, 
        MatSidenavModule, 
        MatToolbarModule, 
        MatListModule, 
        MatTabsModule, 
        MatCardModule, 
        MatSelectModule, 
        MatTableModule, 
        MatSortModule, 
        MatRadioModule, 
        MatDialogModule, 
        MatBadgeModule]
})

export class MaterialModule{}